<a href="https://colab.research.google.com/github/Rajesh165/test/blob/master/Farmer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

In [2]:
df = pd.read_csv('/content/filename.csv')
df.head()

   Unnamed: 0  temp(cel)  ...   district  month_index
0           0  12.571663  ...  Bhagalpur            1
1           1  16.876908  ...  Bhagalpur            1
2           2  15.775776  ...  Bhagalpur            1
3           3  12.903226  ...  Bhagalpur            1
4           4  16.829754  ...  Bhagalpur            1

[5 rows x 9 columns]

In [3]:
df['district'].unique()

array(['Bhagalpur', 'chapra', 'Darbhanga', 'Dehri', 'Forbesganj', 'Gaya',
       'jamui', 'Motihari', 'Muzaffarpur', 'patna', 'Purnea', 'Raxaul',
       'Sabour', 'Supaul'], dtype=object)

In [4]:
df = df.sample(frac=1).reset_index(drop=True)
df.head()

   Unnamed: 0  temp(cel)  ...     district  month_index
0         327  30.249077  ...       Purnea            5
1         228   9.323347  ...     Motihari            1
2         250  28.505738  ...  Muzaffarpur            8
3         363  20.321127  ...       Raxaul            1
4         276  30.835069  ...        patna            6

[5 rows x 9 columns]

In [5]:
X=df[['temp(cel)','mean_windspeed(km/hr)','re_hum(%)','cloud(okta)','rain(mm)','avg._no._rainyday','month_index']]
y =df['district']

In [6]:
X

      temp(cel)  mean_windspeed(km/hr)  ...  avg._no._rainyday  month_index
0     30.249077               5.992444  ...                5.7            5
1      9.323347               3.513469  ...                1.4            1
2     28.505738               5.568657  ...               11.5            8
3     20.321127               3.822299  ...                1.3            1
4     30.835069               6.978292  ...                5.3            6
...         ...                    ...  ...                ...          ...
5105  27.496660               3.486644  ...               11.2            9
5106  16.443751               4.076211  ...                0.5           11
5107  30.306671               4.891453  ...               11.5            8
5108  33.293983               7.719567  ...                0.7            4
5109  29.686339               5.201331  ...               12.2            8

[5110 rows x 7 columns]

In [7]:
y

0            Purnea
1          Motihari
2       Muzaffarpur
3            Raxaul
4             patna
           ...
5105         Purnea
5106           Gaya
5107    Muzaffarpur
5108           Gaya
5109         chapra
Name: district, Length: 5110, dtype: object

In [8]:

lb = preprocessing.LabelEncoder()
y=lb.fit_transform(y)
y

array([ 7,  5,  6, ...,  6,  4, 11])

In [9]:
X = X.iloc[:,:].values
X

array([[ 30.24907705,   5.99244423,  72.82253867, ..., 126.15877078,
          5.7       ,   5.        ],
       [  9.32334665,   3.51346918,  81.62556327, ...,  12.88604363,
          1.4       ,   1.        ],
       [ 28.50573821,   5.56865708,  83.44975984, ..., 295.27699076,
         11.5       ,   8.        ],
       ...,
       [ 30.3066709 ,   4.89145309,  84.92980773, ..., 296.43742441,
         11.5       ,   8.        ],
       [ 33.29398346,   7.71956682,  38.72529016, ...,  13.00235064,
          0.7       ,   4.        ],
       [ 29.68633939,   5.20133073,  81.03292216, ..., 280.67258794,
         12.2       ,   8.        ]])

In [10]:
  
x_train, x_test, y_train, y_test= train_test_split(X, y, test_size= 0.25, random_state=0)

In [11]:
from sklearn.ensemble import RandomForestClassifier  
classifier= RandomForestClassifier(n_estimators= 10, criterion="entropy")  
classifier.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [12]:
y_pred= classifier.predict(x_test)

In [13]:
y_pred

array([0, 7, 9, ..., 0, 2, 0])

In [14]:
y_test

array([0, 7, 9, ..., 0, 2, 0])

In [15]:
op = lb.inverse_transform(y_test)
op

array(['Bhagalpur', 'Purnea', 'Sabour', ..., 'Bhagalpur', 'Dehri',
       'Bhagalpur'], dtype=object)

In [16]:
#Creating the Confusion matrix  
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred)

In [17]:
cm

array([[ 83,   0,   0,   0,   3,   0,   0,   0,   0,   0,   0,   0,   0,
          2],
       [  0,  80,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0],
       [  0,   0,  85,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0],
       [  2,   0,   0,  93,   0,   0,   1,   2,   0,   0,   0,   0,   0,
          3],
       [  6,   0,   1,   0,  86,   0,   0,   0,   0,   0,   0,   0,   0,
          0],
       [  0,   1,   0,   0,   0,  98,   0,   0,   0,   0,   0,   1,   0,
          0],
       [  0,   0,   0,   0,   0,   0,  78,   2,   0,   0,   0,   1,   0,
          0],
       [  0,   0,   0,   1,   0,   0,   2,  80,   0,   0,   0,   0,   0,
          0],
       [  0,   0,   0,   0,   1,   0,   0,   0,  93,   0,   0,   0,   0,
          0],
       [  2,   0,   0,   0,   0,   0,   1,   0,   3,  95,   0,   0,   0,
          0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  87,   0,   4,
          0],
       [  0,   0,   1,   0,   0,   0,   1,   0,   0,   0,   0,  82,   0,
          0],
       [  0,   0,   0,   1,   0,   0,   0,   1,   0,   0,   3,   0, 100,
          0],
       [  3,   0,   0,   0,   1,   0,   0,   0,   0,   0,   0,   0,   0,
         88]])

In [18]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
# View accuracy score
score = accuracy_score(y_test, y_pred)

In [19]:
score

0.9608763693270735