<a href="https://colab.research.google.com/github/Rajesh165/test/blob/master/farmer1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

In [2]:
df = pd.read_csv('/content/filename.csv')
df.head()

   Unnamed: 0  temp(cel)  ...   district  month_index
0           0  12.571663  ...  Bhagalpur            1
1           1  16.876908  ...  Bhagalpur            1
2           2  15.775776  ...  Bhagalpur            1
3           3  12.903226  ...  Bhagalpur            1
4           4  16.829754  ...  Bhagalpur            1

[5 rows x 9 columns]

In [3]:
df = df.sample(frac=1).reset_index(drop=True)
df.head()

   Unnamed: 0  temp(cel)  ...     district  month_index
0          10  30.744946  ...    Bhagalpur            6
1         152  30.557357  ...   Forbesganj            8
2          66  16.462852  ...    Darbhanga            3
3         269  29.029783  ...  Muzaffarpur            3
4         148  30.642695  ...   Forbesganj            6

[5 rows x 9 columns]

In [4]:

y =df['district']
lb = preprocessing.LabelEncoder()
y=lb.fit_transform(y)
df['district'] = y
df.head()

   Unnamed: 0  temp(cel)  ...  district  month_index
0          10  30.744946  ...         0            6
1         152  30.557357  ...         3            8
2          66  16.462852  ...         1            3
3         269  29.029783  ...         6            3
4         148  30.642695  ...         3            6

[5 rows x 9 columns]

In [5]:
X=df[['temp(cel)','mean_windspeed(km/hr)','re_hum(%)','cloud(okta)','rain(mm)','avg._no._rainyday','district']]
y =df['month_index']
X

      temp(cel)  mean_windspeed(km/hr)  ...  avg._no._rainyday  district
0     30.744946               5.527376  ...                8.2         0
1     30.557357               7.815268  ...               13.3         3
2     16.462852               3.829309  ...                0.7         1
3     29.029783               3.242511  ...                0.6         6
4     30.642695              10.175033  ...               10.0         3
...         ...                    ...  ...                ...       ...
5105  16.024355               2.602976  ...                0.3        13
5106  31.190129               4.949395  ...                1.0         5
5107  27.238584               6.543153  ...                3.5         0
5108  26.353608               4.885859  ...                3.1         6
5109  21.849303               3.103965  ...                0.9         0

[5110 rows x 7 columns]

In [6]:
y

0        6
1        8
2        3
3        3
4        6
        ..
5105    11
5106     4
5107     5
5108     5
5109     1
Name: month_index, Length: 5110, dtype: int64

In [7]:
x_train, x_test, y_train, y_test= train_test_split(X, y, test_size= 0.25, random_state=0)

In [8]:
from sklearn.ensemble import RandomForestClassifier  
classifier= RandomForestClassifier(n_estimators= 10, criterion="entropy")  
classifier.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [10]:
import joblib
filename = 'month_index.csv'
joblib.dump(classifier,filename)

['month_index.csv']

In [11]:
model = joblib.load('month_index.csv')
y_pred = model.predict(x_test)
y_pred

array([ 7,  6, 10, ..., 10,  6,  9])

In [12]:
y_test

42       7
380      6
3524    10
352      9
4927     6
        ..
4866     9
1657     7
982     10
3679     6
4803     9
Name: month_index, Length: 1278, dtype: int64

In [13]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
# View accuracy score
score = accuracy_score(y_test, y_pred)
score

0.9835680751173709