<a href="https://colab.research.google.com/github/Rajesh165/test/blob/master/farmer1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

In [2]:
df = pd.read_csv('/content/filename.csv')
df.head()

   Unnamed: 0  temp(cel)  ...   district  month_index
0           0  12.571663  ...  Bhagalpur            1
1           1  16.876908  ...  Bhagalpur            1
2           2  15.775776  ...  Bhagalpur            1
3           3  12.903226  ...  Bhagalpur            1
4           4  16.829754  ...  Bhagalpur            1

[5 rows x 9 columns]

In [3]:
df = df.sample(frac=1).reset_index(drop=True)
df.head()

   Unnamed: 0  temp(cel)  ...   district  month_index
0         190  26.172134  ...      jamui            9
1          73  26.969323  ...  Darbhanga            8
2         275  25.632595  ...      patna            2
3         177  23.394200  ...       Gaya            1
4         184  27.427941  ...      jamui            9

[5 rows x 9 columns]

In [4]:

y =df['district']
lb = preprocessing.LabelEncoder()
y=lb.fit_transform(y)
df['district'] = y
df.head()

   Unnamed: 0  temp(cel)  ...  district  month_index
0         190  26.172134  ...        12            9
1          73  26.969323  ...         1            8
2         275  25.632595  ...        13            2
3         177  23.394200  ...         4            1
4         184  27.427941  ...        12            9

[5 rows x 9 columns]

In [5]:
X=df[['temp(cel)','mean_windspeed(km/hr)','re_hum(%)','cloud(okta)','rain(mm)','avg._no._rainyday','district']]
y =df['month_index']
X

      temp(cel)  mean_windspeed(km/hr)  ...  avg._no._rainyday  district
0     26.172134               4.992250  ...               10.2        12
1     26.969323               4.930442  ...               10.6         1
2     25.632595               2.788494  ...                0.8        13
3     23.394200               4.560738  ...                0.9         4
4     27.427941               3.815249  ...               10.2        12
...         ...                    ...  ...                ...       ...
5105  28.638292               4.116336  ...               11.2         7
5106  27.036183              10.946695  ...                7.5         8
5107  17.518152               4.336984  ...                1.4         2
5108  26.494927               3.879178  ...               16.7         7
5109  29.342662               7.100267  ...                7.8         8

[5110 rows x 7 columns]

In [6]:
y

0       9
1       8
2       2
3       1
4       9
       ..
5105    9
5106    6
5107    2
5108    7
5109    9
Name: month_index, Length: 5110, dtype: int64

In [7]:
x_train, x_test, y_train, y_test= train_test_split(X, y, test_size= 0.25, random_state=0)

In [8]:
from sklearn.ensemble import RandomForestClassifier  
classifier= RandomForestClassifier(n_estimators= 10, criterion="entropy")  
classifier.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [9]:
y_pred= classifier.predict(x_test)  
y_pred

array([ 4, 10,  3, ...,  1,  3, 11])

In [10]:
y_test

42       4
380     10
3524     3
352      6
4927     1
        ..
4866    10
1657     2
982      1
3679     3
4803    11
Name: month_index, Length: 1278, dtype: int64

In [11]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
# View accuracy score
score = accuracy_score(y_test, y_pred)
score

0.9859154929577465